name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_SERVER }}
          user: "lct"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "pdfParseService"